widevine: CB2 OEMCrypto_BuildInformation json format wrong [1/1]
PD#SWPL-143779

Problem:
gts/wvts testOemCryptoBuildInfoJson
org.json.JSONException: Expected literal value at character

Solution:
Remove last "," for josn data

Verify:
S905X4 & Android-U

Build Tag:
Android_U_DRM_PATCHBUILD-858

Commits:
vendor/amlogic/common/widevine:
version: 18.4-r0.1-ge180885(build:858)
e180885 widevine: CB2 OEMCrypto_BuildInformation json format wrong [1/1]

vendor/amlogic/common/tdk:
e168db0 permission: modify TEE device node permissions [1/1]

vendor/amlogic/common/tdk_v3.8/ta_export:
be954c1 commit 28d164eae659a13455ae229353cba78abcbe5437
Author: gerrit.automerge <gerrit.automerge@amlogic.com>
Date:   Thu Jul 20 17:02:05 2023 +0800

vendor/amlogic/common/tdk_v3.18/ta_export:
715bf85 commit b24ff5c61cf86a1ee2c342cb9c191c4f29c67500
Author: Lawrence Mok <lawrence.mok@amlogic.com>
Date:   Mon Jan 30 16:31:33 2023 -0800

vendor/widevine/libwvmediacas:
7aa9fc3 wvcas: CB1 Make wvcas plugin v17 work with opk v18 [1/1]
0866f19 V17.2.0 CAS plugin

vendor/amlogic/common/widevinecas:
version: 16.4-r14-g991ded4(build:858)
991ded4 wvcas: CB2 Google wvcas test streams playback failed [1/1]

Git Hash-Object:
46b9f7c14517c042a0a0088af8ed49e430d867d6
test/arm/wvcas_iptv_test
917d052485b73b0d497f0aa0ec77ac1626bf8395
test/arm/wvcas_iptv_test_sys
0ac4efba9814fa7ee5f50971a59f1ae7d47d6913
wvcas/arm/libdec_ca_wvcas.so
d32f19801375e3e661fa6503b54e4d5472fb070c
wvcas/arm/libdec_ca_wvcas.system.so
f1c4a64d942422ecb0d92c57243b14b90974905f
wvcas/ta/v2/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
cc7ae5f08a9c6b57bc4adda5bbdc9a36ef0280e5
wvcas/ta/v2/signed/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
4b749a0eb3b5e9ffc60089d3aafe79967a328e55
wvcas/ta/v3/dev/A311D2/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
964a7768a16e23fc740fdf1516728e2244fa4f60
wvcas/ta/v3/dev/S805X2/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
957771aed8504319644d39b12f1bf25acabbf1d5
wvcas/ta/v3/dev/S805X2G/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
13fa093ab8039730de41581c24048f1977ff0939
wvcas/ta/v3/dev/S905C2/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
872d95dbe041f5710791f68a77ca83aa0df1e8d3
wvcas/ta/v3/dev/S905C2L/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
760b0f7ef0c7fba3357c1fb3d423dab28213e45e
wvcas/ta/v3/dev/S905C3/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
189f656740f14eaac8b5c391c690b93c8a9c1bbb
wvcas/ta/v3/dev/S905X4/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
18bf51d4feb1ff3ec121c338ec3af5c6184ce47f
wvcas/ta/v3/dev/S905Y4/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
4618de4e9c5c0fe8db8b8d2ca74da5981ea2693b
wvcas/ta/v3/dev/S928X/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
436a31ecad395f925a9614734bd063d92712dc3d
wvcas/ta/v3/dev/T963D4/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
4bfe046bb986cbf066a44ae0ba79b401592310f0
wvcas/ta/v3/dev/T965D4/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
4add338a27015a98fe74af5e6d3cb7b0a10489ab
wvcas/ta/v3/dev/T982/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
7b0917bcae3cacfa945d9b8ef3f0a4636c4c47a1
wvcas/ta/v3/dev/T985/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
5f778c1bac67c11ea7d2432f519ec0efd6e4f187
wvcas/ta/v3/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
7c0c58b9f0d49ce4c1bc3ad148c5c326c230d734
wvcas/ta/v3/signed/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
b9a6119e386fc29f707acce3d98892a5e818c471
wvcas/ta/v3/tdk-v3.18-64bit/e043cde0-61d0-11e5-9c26-0002a5d5c5ca.ta
85d6b41e2fbaf569ec53030c75f176cde1be9c4a
wvcenc/arm/liboemcrypto.so
5e8f404f05d99fe0b949a888b636f03747da17e3
wvcenc/arm64/liboemcrypto.so
6b9d69442dcda2eebf298cdd25437eace912a7c9
wvcenc/ta/v2/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
5a75e19f3dd2d1d0682886d5fefacc0aed3502a2
wvcenc/ta/v2/signed/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
c7c76e1241a993358378c19a33426dee684d5851
wvcenc/ta/v3/dev/A311D2/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
999272fa99482327a6ac94d027c14abbfcb6988c
wvcenc/ta/v3/dev/S805X2/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
4ed01f85a2a2fac1cc70af065159069af57fd812
wvcenc/ta/v3/dev/S805X2G/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
2f4c732634e004c0df5d0260efda69c8ecbc31da
wvcenc/ta/v3/dev/S905C2/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
92b31aee191ccdedc311d309e55b36f4873bf793
wvcenc/ta/v3/dev/S905C2L/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
7416ac33d945a4e81ae67591dad4c4d069abf8bf
wvcenc/ta/v3/dev/S905C3/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
1973a3ff7da76b7e2f5f24e24a5cde92961463c4
wvcenc/ta/v3/dev/S905X4/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
c30a0f7d5fd964b2a1b447a09dee236a4d462062
wvcenc/ta/v3/dev/S905Y4/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
063039127af4b916e186a663e04b411bc6b3bc01
wvcenc/ta/v3/dev/S928X/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
54182b9fefbdcda520c090848241e8565d4923a4
wvcenc/ta/v3/dev/T963D4/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
a947f48b6463e738883bfe01356a0c0a38e8e49c
wvcenc/ta/v3/dev/T965D4/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
0000000000000000000000000000000000000000
wvcenc/ta/v3/dev/T968D4/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
d9eb746d342298b660044395e315044ad775be4c
wvcenc/ta/v3/dev/T982/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
6cb08c14867fd362ba55c316d9cc68249187b878
wvcenc/ta/v3/dev/T985/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
374ea8741bb7b1c17aabc7e048a136f9f98032c3
wvcenc/ta/v3/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
9c8d086e6f31ff0a3f499d1b78d6610a6dd36780
wvcenc/ta/v3/signed/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta
e5acf1af37a14d923d71ee981b387ee083a142c2
wvcenc/ta/v3/tdk-v3.18-64bit/e043cde0-61d0-11e5-9c26-0002a5d5c51b.ta

Change-Id: Iac615dcbfc9714f3c5fbc22195a4b0a3411ebc3b
Signed-off-by: DRM Auto Build <tao.guo@amlogic.com>